# OpenAI Configuration
quarkus.langchain4j.openai.api-key=${QUARKUS_LANGCHAIN4J_OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini


# Application Configuration
quarkus.http.port=8080

# Database Configuration
# Dev Services will automatically start a PostgreSQL container in dev mode
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true
